name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/j1cken/mongodb-kafka-connect:0.40.0-kafka-3.7.0
    - name: Push
      run: docker push quay.io/j1cken/mongodb-kafka-connect:0.40.0-kafka-3.7.0
